#ifndef GLVIEWERLIB_GLOBAL_H
#define GLVIEWERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GLVIEWERLIB_LIBRARY)
#  define GLVIEWERLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GLVIEWERLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GLVIEWERLIB_GLOBAL_H
